### ISSUE TITLE
unify projects: gpstime

### ISSUE THREAD

**Issue by jrollins** [the-aerospace-corporation/gps_time#16]
I just want to highlight the existence of [gpstime](https://pypi.org/project/gpstime/), and that it might be nice if the projects were unified.

**Comment by davidallen353** [comment]
Thanks! It may be useful to use their implementation for leap seconds, but one of the goals for this project was to have sufficient resolution for calculations related to GPS/GNSS. 

gpstime inherits from the builtin `datetime` class that is limited to microsecond resolution, which is inadequate for navigation.
